入力された期間をカレンダー表示する機能追加
kitazawasyogo/console-calendar pull request #13
Opened 2022-12-21 08:19 UTC by kitazawasyogo

@nabemasamasa @Takatatsu9
入力された期間をカレンダー表示する機能追加を行いました。
お忙しいかと思いますが、レビューよろしくお願いいたします。

2022-12-22 02:16 UTC, nabemasamasa reviewed
Qあり。

2022-12-22 02:16 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +            If flowMonth > 12 Then
[VB.NET.コーディングルール.md#61-大小比較演算子](https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#61-%E5%A4%A7%E5%B0%8F%E6%AF%94%E8%BC%83%E6%BC%94%E7%AE%97%E5%AD%90)

2022-12-23 02:52 UTC, Takatatsu9 reviewed
Done

2022-12-23 02:52 UTC, Takatatsu9 commented on DisplayCalendar.vb
> +
[Q] この唐突に出てきた`Console.WriteLine()`はなんですか？
「入力された期間をカレンダー表示する機能追加」に関係があるようには思えませんけど。

2022-12-23 02:52 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        For flowMothNumber As Integer = 0 To lastMonth
[nits] typoしてない？`Moth`

2022-12-23 02:52 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +    Private Function ConfirmInputValue() As String
[IMO] メソッド名とコメントが一致しない

2022-12-23 02:56 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +                Dim inputEndArray As String() = inputValueArray(1).Split("/"c)
@kitazawasyogo 質問に回答しないのはなぜですか？
👀 がついてるってことはもう読んでますよね？

2022-12-23 02:56 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
@kitazawasyogo 質問に回答しないのはなぜですか？
それとも回答はサムズアップをもって代えさせて頂きますということですか？

2022-12-23 06:07 UTC, Takatatsu9 commented on DisplayCalendar.vb
> +
@kitazawasyogo 既読無視やめてくださいますか＾＾；

2022-12-23 07:15 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +                Dim inputEndArray As String() = inputValueArray(1).Split("/"c)
配列の長さチェックをする場所を間違えていました。
値を使用する前にチェックが行われるよう、適切な場所に移動しました。

2022-12-23 07:16 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
インスタンスを作る意味と、宣言と同時に代入しなかった理由は特にありません。
修正いたしました。
（自分でDateTimeの使用方法を調べた時に出てきた資料そのままの形で書き、コーディングルールを見落としてしまいました。）

2022-12-23 07:17 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
DateTimeの部分でエラーになります。
yyyyは桁数のチェックだけで大丈夫ですが、MMは12月迄しかないので数値が範囲内かチェックが必要だと思います。
例外処理の条件に書き加える必要があるので追加します。

2022-12-23 07:18 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Dim nextYear As Integer = Nothing
整数を代入する型(integer)に参照型のNothingを代入してしまいました。
Nothingではなく0に変更しました。

コメントのどうなるのか？という質問の回答は分かりません。構文が間違えていることは分かります。
（動作は問題ないが、警告が出るのでしょうか？）

2022-12-23 07:18 UTC, kitazawasyogo commented on DisplayCalendar.vb
> +
別のメソッドの機能と改行されずに画面表示されてしまうので、今回の「入力された期間をカレンダー表示する機能追加」の前に画面表示される機能の最期に改行を追加しました。

2022-12-23 07:18 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +    Private Function ConfirmInputValue() As String
コメントの方は正しいと思うのでメソッド名見直します。

2022-12-23 07:38 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/console-calendar/pull/13#discussion_r1056064739
質問に回答する指示に気づいていませんでした。今気づきました。申し訳ありません。

解決できて対応済みになったらまとめて返信し、不明点はまとめて質問しようと考えていました。

2022-12-23 07:59 UTC, Takatatsu9 commented
いや[Q]の質問には答えるってknowledgeに書いてませんでしたか？
（というか過去のPRでちゃんと回答してたじゃないですか）

2022-12-23 08:02 UTC, nabemasamasa commented
> 解決できて対応済みになったらまとめて返信し、不明点はまとめて質問しようと考えていました。

それは、非効率な、よくない考えだと思います。
対応してから返信した結果を見た相手からのレスポンスで、対応した部分は実は自分の早合点で修正しなくてよかった、もっと別の修正をすべきだった、とかだったら無駄じゃありませんか？
それだったらまず回答を返してその中で「これから修正します！」宣言した方が、もし間違った修正をしそうになっても途中で軌道修正できるから、良くないですか？

2022-12-23 08:02 UTC, kitazawasyogo commented
> いや[Q]の質問には答えるってknowledgeに書いてませんでしたか？ （というか過去のPRでちゃんと[Q]に対して回答してたじゃないですか）

2022-12-23 08:03 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +                Dim inputEndArray As String() = inputValueArray(1).Split("/"c)
「質問」の場合、まず「質問」に対して「回答」してほしいです。

一応、流れで次のように読み取りはしたんですけど、
「IndexOutOfRangeExceptionが発生する」はYESで、だから「コードが間違ってるので、修正します」ってことですよね？

2022-12-23 08:13 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +                Dim inputEndArray As String() = inputValueArray(1).Split("/"c)
[Q]の場合まず回答を行うようにします。

その通りです。

2022-12-23 08:15 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
回答ありがとう、それは資料が悪い……とは言いません。
参考にしたコードを意味を理解せず、**そのまま採用する** のはＮＧです。
(コピペ禁止。参考にしたサイトそのままコピペしました！使ってるメソッドとか処理は説明できないですが動きます！とまで言えばわかるかな)

コーディングルールというか、どちらかというと使用しないのにインスタンス生成している、とか1行で書けるのに冗長な書き方をする、とか「無駄」が焦点です。

2022-12-23 08:23 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +            Dim nextYear As Integer = Nothing
IntegerはNull値を取らない型だから、初期値に0が入ってたり、Nothing代入しても0になったはず。
Nullも代入したいなら、型に`?`を付ける必要がある(ex: `Integer?`)
でも、直後のIf文でどっち通っても値が必ずセットされるなら、ここで初期値設定する意味はないと思う。

2022-12-23 08:25 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
確認ありがとうございます！はい、私も追加で入力チェックが必要だと思うので、追加お願いします。

2022-12-26 00:05 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Dim beginningDt As DateTime = DateTime.Parse(beginningDay)
AddMonthを初めて知りました。
見直してみます。

2022-12-26 00:06 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +                ElseIf Not inputBeginningArray.Length = 2 OrElse Not IsNumeric(inputBeginningArray(0)) OrElse Not IsNumeric(inputBeginningArray(1)) OrElse Not inputBeginningArray(0).Length = 4 OrElse
メソッド抽出して共通化行ってみたいと思います。

今回の様に２回以上同じ事をしていたらメソッド抽出して共通化した方がいいのでしょうか。
必ず行わなくてもよいものであれば、メソッド抽出するべきものとそうでないものの基準などあるのでしょうか。

2022-12-26 05:20 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +                ElseIf Not inputBeginningArray.Length = 2 OrElse Not IsNumeric(inputBeginningArray(0)) OrElse Not IsNumeric(inputBeginningArray(1)) OrElse Not inputBeginningArray(0).Length = 4 OrElse
同じ仕様(知識とか意味とか)を表現しているなら共通化した方がよく、別々の仕様が同じコードで書かれてる場合は共通化は避けた方がいいと思います。
「DRY原則」で調べてみると、具体例など見つかると思います。

2023-01-12 04:23 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +    Private Function ConfirmInputValue() As String
コメントをメソッド名に合わせて修正しました。

2023-01-12 04:32 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Dim beginningDt As DateTime = DateTime.Parse(beginningDay)
コメントありがとうございます。
正しい方法ではないからかもしれませんが、私はAddMonthを使用しない方がコードが簡潔になり楽かと思いました。
[imo]ですので今回はAddMonthを使用しない方法にさせて頂きたいと思います。

2023-01-12 04:55 UTC, kitazawasyogo commented
複数の内容が混ざったコミットをPushしてしまった為、コミットを分けて強制プッシュいたしました。

2023-01-12 05:33 UTC, Takatatsu9 requested changes
Done

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +    Private Function CheckYearAndMonthValue(checkInputArray As String()) As Boolean
[MUST] `Check～`というメソッド名は問題なければTrueなのか問題あればTrueなのかわからないのでダメです。
コーディングルールにもそう書かれている。

我々は`Validate～`（問題なければTrue）というのを使っています。

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
[IMO] 引数に例外起きたときのメッセージ書けるので、何が悪いのかが書いてあると良い

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +
> コーディングルールに違反している為、修正

[Q] この改行は何に違反していた為追加したんですか？

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        For flowMonthNumber As Integer = 0 To lastMonth
これはコーディングルール違反じゃなくてただのtypoですよね

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +    ''' 入力値の確認
これはコーディングルール違反じゃなくてただのコメントミスですよね

2023-01-12 05:33 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +                End If
これはコーディングルール違反じゃなくてただのエラーチェック漏れですよね

2023-01-12 05:49 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +
違反していません間違いです。他のメソッドと合わせるため改行を追加しました。

・同じ処理を２回行っている為、メソッド抽出して共通化
・コーディングルールに違反している為、修正

・その他修正部分のコミット
・

と分ける必要がありました。

2023-01-12 05:56 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        For flowMonthNumber As Integer = 0 To lastMonth
コーディングルール違反ではなくtypoでしたのでrenameしました。

2023-01-12 05:56 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +    ''' 入力値の確認
こちらもコーディングルール違反ではなくコメントミスです。

2023-01-12 05:56 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +                End If
コーディングルール違反ではなくエラーチェック漏れです。

2023-01-12 06:01 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
入力チェックで使われるメソッド名には、`Validate`始まり以外にも`Assert`始まりが使える。
んだけど……
・`Validate`を使うシチュエーションは、入力チェックの結果OKならTrue、BadならFalseを返して、その結果を使って処理をさせる
・`Assert`を使うシチュエーションは、整合性が取れてない場合は例外を発生させる。整合性が取れてなければFalseを返さないので`~~~ Sub AssertXXX`

パッと見た感じ、このメソッドはどっちつかずなので、どっちを使った方がよいと言えないんですが、
メソッド名`Validate～～`にするなら以下みたいにValidateの結果で例外投げてほしいし
```vb
If Not ValidateXXX() Then
    Throw XXXException
End If
```
メソッド名`Assert`にするなら、Public Sub～～で不整合の条件と一致したら例外投げるだけ、に寄せたいです。

2023-01-12 06:07 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
回答では「修正いたしました」だけど、Pushされたコミットにはなさげ。
消えちゃいました？

2023-01-12 06:09 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +            Dim beginningDt As DateTime = DateTime.Parse(beginningDay)
了解です。検討ありがとう。

2023-01-12 06:10 UTC, nabemasamasa commented on DisplayPeriodCalendar.vb
> +            Dim inputValueBeginningMonth As String = inputBeginningArray(0) & inputBeginningArray(1)
「文字列結合なら`&`使いたいな…」は`[nits]`で、コーディングルール違反だったら`[MUST]`でツッコミしてたと思うんだけど……。
[Q] もしかして、これ、コーディングルール違反だった？

2023-01-12 06:12 UTC, nabemasamasa reviewed
done (コミットコメントと一致しない修正含み過ぎじゃない？)

2023-01-12 06:27 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
つまりこうじゃ

メソッドをIf文に組み込む？→YES→`Function Validate～`
　　　NO↑　↓NO
メソッド内で例外投げる？→YES→`Sub Assert～`

2023-01-12 06:27 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        inputValueBeginningYear = Convert.ToDateTime(inputValueArray(1))
消えてしまいました。修正します。

2023-01-12 06:32 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Dim inputValueBeginningMonth As String = inputBeginningArray(0) & inputBeginningArray(1)
コーディングルール違反でないと思います。
コミットコメントと一致しない修正を含んでしまいました。

2023-01-12 06:36 UTC, kitazawasyogo commented
これから行う修正として
・先程の２つのコミットをreset
・コミットコメントと一致するようにコミットを分け、pushし直す
・今回頂いたレビューの対応を行う

で正しいでしょうか。

もしくは先程の2つのコミットをresetせずに残し、次回以降正しいコミットコメントと内容でコミットした方が良いのでしょうか。

2023-01-12 06:45 UTC, Takatatsu9 commented
まず先に前2つをやってpushしたあと、3つ目をやったほうがいいですね。
それと箇条書きは番号振ってくれると指しやすくて助かります。

2023-01-13 01:53 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
コメントありがとうございます。
こちらのコメント実際に何をすれば良いのか理解できていません。

コメントを書いておくという事でしょうか。

2023-01-13 01:55 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
引数がわからないってことですか？

2023-01-13 02:13 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
引数自体は分かります。
引数のどの場所に書くのでしょうか

2023-01-13 02:14 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
第1引数です

2023-01-13 04:47 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
Catchの部分で表示するメッセージを設定するのではなく例外が起きる場所ごとにそれぞれ適切なメッセージを割り振りArgumentExceptionの第一引数に設定したメッセージを表示するように変更するで正しいでしょうか。

2023-01-13 05:00 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +            Throw New ArgumentException
前半何言ってるのかさっぱりわかりませんが、

> ArgumentExceptionの第一引数に設定

これが私が指摘したあると良い変更です

2023-01-13 05:44 UTC, kitazawasyogo commented
コミットコメントと一致するようにコミットを内容ごとに分けPushしました。
前回頂いたレビューの対応も行いましたのでレビューお願いいたします。

2023-01-16 05:56 UTC, nabemasamasa reviewed
Done!

2023-01-16 07:14 UTC, kitazawasyogo commented
コミット整理を行い強制プッシュいたしました。
[変更点](https://github.com/kitazawasyogo/console-calendar/compare/09ca47471236ba84912468d4a41a887bd06a3587..e857fcf21ecfb833d9d6687792655702dbefe2b0)はございません。

Issue[番外]をこちらのPRにリンク付けする場合は引き続きこちらのPRを使用したいと思います。
新しくIssue[番外]のPRを作成した方が良い場合はこちらのPRマージしてよろしいでしょうか。

2023-01-16 08:25 UTC, nabemasamasa commented
#14 ですよね。個別でPR作って紐づけるのが望ましいです。
マージ良いと思います。

2023-01-17 06:22 UTC, Takatatsu9 reviewed
Done

2023-01-17 06:22 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        If 13 < monthValue Then
[Q1] 「≦」ではなく「＜」ということは13月を許容するってことですか？
[Q2] 0以下チェックはありませんが、絶対に無い想定ですか？
（無い場合もある場合もその根拠を一緒にお願いします）

2023-01-17 07:03 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        If 13 < monthValue Then
レビューありがとうございます。

「1」ご指摘ありがとうございます。ミスです。13月許容しないので「≦」が正しいので修正いたします。
「2」０以下が入力されエラーが起こる事を想定できていませんでした。エラーチェック漏れです。

０以下の値(yyyy/00)が入力されエラーが起こってしまうと思います。０以下チェックを条件に追加いたします。

2023-01-17 07:27 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        If 13 < monthValue Then
こういう修正をする際は、さっさとコード修正して終わり！じゃなくて、
まず実際に入力してみて問題が発生するかを試してみてくださいね。

あとその結果知りたいので検証したら書き込んでください。

2023-01-17 07:47 UTC, kitazawasyogo commented on DisplayPeriodCalendar.vb
> +        If 13 < monthValue Then
問題が発生するか入力確認
1. 「＜」では13が許容してしまいハンドルされていない例外が発生しました。
2. yyyy/00が入力された際、ハンドルされていない例外が発生しました。

2023-01-17 23:11 UTC, kitazawasyogo commented
修正を行いPushいたしました。
コミットはこちらですhttps://github.com/kitazawasyogo/console-calendar/pull/13/commits/c9db1a29e5e3386695bbcf717da2b2cda1ebd0c8

レビューお願いいたします。

2023-01-18 00:14 UTC, nabemasamasa reviewed
Done!

2023-01-18 00:14 UTC, nabemasamasa approved these changes

2023-01-18 07:41 UTC, Takatatsu9 approved these changes
Done

2023-01-18 07:41 UTC, Takatatsu9 commented on DisplayPeriodCalendar.vb
> +        If 13 <= monthValue OrElse monthValue <= 0 Then
[nits] 個人的には逆のほうが好み。個人的なんで直さなくてもいい
```vb
' 範囲内か？というのを知りたい場合、検証したい値を内側にもってくる
If 10 <= value AndAlso value <= 20 Then 〜

' 範囲外か？というのを知りたい場合、検証したい値を外側にもっていく
If value < 10 OrElse 20 < value Then 〜

```

2023-01-18 07:55 UTC, kitazawasyogo commented
コミット整理を行い強制プッシュいたしました。
[変更点](https://github.com/kitazawasyogo/console-calendar/compare/c9db1a29e5e3386695bbcf717da2b2cda1ebd0c8..b4ac0fd5627f10029a0ac5415386dca52809e684)はございません。

マージしてよろしいでしょうか。

2023-01-18 08:00 UTC, merged